apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otel-tail-sampler.fullname" . }}
  labels:
    {{- include "otel-tail-sampler.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "otel-tail-sampler.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otel-tail-sampler.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          ports:
            - name: otlp
              containerPort: {{ .Values.config.receiver.grpc_port }}
              protocol: TCP
            - name: gossip
              containerPort: {{ .Values.config.gossip.port }}
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /data
            - name: config
              mountPath: /etc/otel-sampler
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.persistence.enabled }}
          emptyDir: {} # Simplified for prototype, ideally persistentVolumeClaim
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config
          configMap:
            name: {{ include "otel-tail-sampler.fullname" . }}-config
