apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-tail-sampler.fullname" . }}-headless
  labels:
    {{- include "otel-tail-sampler.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.config.gossip.port }}
      targetPort: gossip
      protocol: TCP
      name: gossip
  selector:
    {{- include "otel-tail-sampler.selectorLabels" . | nindent 4 }}
