apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp/ingress:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
      otlp/egress:
        protocols:
          grpc:
            endpoint: 0.0.0.0:5317

    exporters:
      otlp/sampler:
        endpoint: sampler-service:4317
        tls:
          insecure: true
      debug:
        verbosity: detailed

    service:
      pipelines:
        traces/ingress:
          receivers: [otlp/ingress]
          exporters: [otlp/sampler]
        traces/egress:
          receivers: [otlp/egress]
          exporters: [debug]
        metrics/ingress:
          receivers: [otlp/ingress]
          exporters: [otlp/sampler]
        metrics/egress:
          receivers: [otlp/egress]
          exporters: [debug]
        logs/ingress:
          receivers: [otlp/ingress]
          exporters: [otlp/sampler]
        logs/egress:
          receivers: [otlp/egress]
          exporters: [debug]
